# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'falockAPP20' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for falockAPP20
  pod 'Firebase'
  pod ‘Firebase/Database’
  pod ‘Firebase/Core’ 



end
